/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely';

export type Decimal = ColumnType<string, number | string>;

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Category {
  id: Generated<number>;
  name: string;
}

export interface Image {
  id: Generated<number>;
  productId: number;
  url: string;
}

export interface Product {
  availabilityStatus: Generated<'In Stock' | 'Low Stock' | 'Out of Stock'>;
  brand: Generated<string>;
  categoryId: number | null;
  description: string;
  dimensions: Json;
  discountPercentage: Decimal | null;
  id: Generated<number>;
  meta: Json;
  minimumOrderQuantity: number;
  price: Decimal;
  rating: Decimal;
  returnPolicy: string;
  shippingInformation: string;
  sku: string;
  stock: number;
  thumbnail: string;
  title: string;
  warrantyInformation: string;
  weight: Decimal;
}

export interface ProductToTag {
  productId: number;
  tagId: number;
}

export interface Review {
  comment: string;
  date: Generated<Date>;
  id: Generated<number>;
  productId: number;
  rating: Decimal;
  reviewerEmail: string;
  reviewerName: string;
}

export interface Tag {
  id: Generated<number>;
  name: string;
}

export interface DB {
  category: Category;
  image: Image;
  product: Product;
  productToTag: ProductToTag;
  review: Review;
  tag: Tag;
}
